security:
  jwt:
    token:
      secret-key: 54cr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:myslq://localhost:3306/DBTed
    username: SA
    password: reallyStrongPwd123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: false
springdoc:
  swagger-ui:
    use-root-path: true

      #server:
      # servlet:
      #   contextPath: /tedBackEnd




