
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DBTed?useTimezone=true&serverTimezone=UTC
    username: SA
    password: reallyStrongPwd123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: false
springdoc:
  swagger-ui:
    use-root-path: true

        #server:
        # servlet:
        #   contextPath: /alunoOnline






